"""
Day 3: the agent layer. Reads a natural-language query, decides which
tool(s) from tools.py it needs, calls them, and returns a response.

This is a RULE-BASED router, not an LLM: a fixed priority list of regex
patterns decides intent, and more regexes pull out arguments (genres,
runtime, year ranges) from the query text. That makes it fully
inspectable (every routing decision comes with a "reason" you can read)
and free to run, at the cost of being less forgiving of phrasing it
wasn't written to expect than a real LLM router would be.

Routing priority (checked in this order, first match wins):
    1. compare_titles   - "compare X and Y", "X vs Y", "difference between X and Y"
    2. mixed lookup+recommend - "something like X but shorter/longer"
    3. recommend         - "recommend"/"suggest"/"looking for" + free description
    4. filter_by_constraints - query is mostly structural (genre/year/runtime/rating)
    5. search_titles      - fallback: treat it as a title/keyword lookup

This is a shared module - other scripts import it, it isn't run directly.
"""

import re

import tools

COMPARE_RE = re.compile(r"\bcompare\b|\bvs\.?\b|\bversus\b|\bdifference between\b", re.I)
LIKE_RE = re.compile(r"(?:^|\s)(?:like|similar to)\s+(.+?)(?:\s+but\b|[?.!]|$)", re.I)
RECOMMEND_RE = re.compile(
    r"\brecommend\b|\bsuggest\b|\blooking for\b|\bwant to watch\b|"
    r"\bshow me\b|\bfind me\b|\bwhat should i watch\b",
    re.I,
)

MAX_RUNTIME_RE = re.compile(
    r"(?:under|less than|shorter than|below|max(?:imum)?)\s+(\d+)\s*(hour|hr|minute|min)", re.I
)
MIN_RATING_RE = re.compile(r"rated\s+(?:above|over|at least)\s+(\d+(?:\.\d+)?)", re.I)
DECADE_RE = re.compile(r"from the (\d{4})s", re.I)
AFTER_YEAR_RE = re.compile(r"\bafter (\d{4})\b", re.I)
BEFORE_YEAR_RE = re.compile(r"\bbefore (\d{4})\b", re.I)
EXACT_YEAR_RE = re.compile(r"\b(?:from|in) (\d{4})\b", re.I)
MOVIE_WORD_RE = re.compile(r"\bmovies?\b", re.I)
TV_WORD_RE = re.compile(r"\bshows?\b|\bseries\b|\btv\b", re.I)
LOOKUP_PREFIX_RE = re.compile(r"^(what is|what's|tell me about|describe)\s+", re.I)
LOOKUP_SUFFIX_RE = re.compile(r"\s+about\??$", re.I)


def extract_genres(text):
    text_lower = text.lower()
    return [g for g in tools.known_genres() if g.lower() in text_lower]


def extract_max_runtime(text):
    m = MAX_RUNTIME_RE.search(text)
    if not m:
        return None
    value, unit = int(m.group(1)), m.group(2).lower()
    return value * 60 if unit.startswith("h") else value


def extract_min_rating(text):
    m = MIN_RATING_RE.search(text)
    if m:
        return float(m.group(1))
    if "highly rated" in text.lower() or "well rated" in text.lower():
        return 7.5
    return None


def extract_year_bounds(text):
    m = DECADE_RE.search(text)
    if m:
        decade = int(m.group(1))
        return decade, decade + 9
    m = AFTER_YEAR_RE.search(text)
    if m:
        return int(m.group(1)) + 1, None
    m = BEFORE_YEAR_RE.search(text)
    if m:
        return None, int(m.group(1)) - 1
    m = EXACT_YEAR_RE.search(text)
    if m:
        year = int(m.group(1))
        return year, year
    return None, None


def extract_media_type(text):
    has_movie, has_tv = bool(MOVIE_WORD_RE.search(text)), bool(TV_WORD_RE.search(text))
    if has_movie and not has_tv:
        return "movie"
    if has_tv and not has_movie:
        return "tv"
    return None


def extract_compare_titles(text):
    text = re.sub(r"^\s*compare\s+", "", text, flags=re.I)
    text = re.sub(r"difference between\s+", "", text, flags=re.I)
    parts = re.split(r"\s+(?:vs\.?|versus|and|to)\s+", text, maxsplit=1, flags=re.I)
    if len(parts) == 2:
        return parts[0].strip(" ?.!"), parts[1].strip(" ?.!")
    return None, None


def strip_lookup_phrases(text):
    t = LOOKUP_PREFIX_RE.sub("", text).strip(" ?.!")
    t = LOOKUP_SUFFIX_RE.sub("", t).strip(" ?.!")
    return t


# --- Response formatting (plain templated text built from tool output,
# not generated by a model) -------------------------------------------

def format_comparison(result):
    if "error" in result:
        return result["error"]
    a, b = result["title_a"], result["title_b"]
    lines = [
        f"{a['title']} ({a['year']}) vs {b['title']} ({b['year']})",
        f"Rating: {a['rating']} vs {b['rating']}  (diff {result['rating_diff']:+.2f})",
    ]
    if result["runtime_diff_minutes"] is not None:
        lines.append(f"Runtime: {a['runtime']} min vs {b['runtime']} min "
                      f"(diff {result['runtime_diff_minutes']:+d} min)")
    if result["year_diff"] is not None:
        lines.append(f"Release gap: {result['year_diff']:+d} years")
    lines.append(f"Shared genres: {', '.join(result['shared_genres']) or 'none'}")
    if result["only_in_a"]:
        lines.append(f"Only in {a['title']}: {', '.join(result['only_in_a'])}")
    if result["only_in_b"]:
        lines.append(f"Only in {b['title']}: {', '.join(result['only_in_b'])}")
    lines.append(f"\n{a['title']} plot: {a['plot'][:400]}...")
    lines.append(f"\n{b['title']} plot: {b['plot'][:400]}...")
    return "\n".join(lines)


def format_recommend(result, prefix=None):
    if not result["results"]:
        return "No titles matched those constraints."
    lines = [prefix] if prefix else []
    for i, r in enumerate(result["results"][:5], start=1):
        lines.append(f"{i}. {r['title']} ({r['year']}) - score {r['final_score']:.3f} "
                      f"[semantic {r['semantic_similarity']:.2f}, bm25 {r['bm25_score']:.2f}, "
                      f"genre {r['genre_match']:.2f}, rating {r['rating_score']:.2f}, "
                      f"novelty {r['novelty_score']:.2f}]")
    return "\n".join(lines)


def format_filter(result):
    if not result["results"]:
        return "No titles matched those constraints."
    lines = [f"{result['count']} titles matched. Top results by rating:"]
    for i, r in enumerate(result["results"][:5], start=1):
        lines.append(f"{i}. {r['title']} ({r['year']}) - rating {r['rating']}, "
                      f"runtime {r['runtime']}, genres: {', '.join(r['genres'])}")
    return "\n".join(lines)


def format_lookup(result):
    if not result["results"]:
        return "No matching titles found."
    lines = [f"Found via {result['method']}:"]
    for r in result["results"]:
        lines.append(f"- {r['title']} ({r['year']}) [{r['media_type']}] "
                      f"- {r['genres']} - rating {r['rating']}")
        if r["overview"]:
            lines.append(f"  {r['overview'][:300]}")
    return "\n".join(lines)


# --- The router --------------------------------------------------------

def handle_query(query):
    """
    Route a natural-language query to the right tool(s) and return a dict:
        intent       - which branch matched
        reason       - why it matched, in plain English
        tool_calls   - [(tool_name, arguments), ...] actually made
        result       - the raw structured data from the tool(s)
        response     - a plain-text summary built from that data
    """

    # 1. Comparison
    if COMPARE_RE.search(query):
        title_a, title_b = extract_compare_titles(query)
        if title_a and title_b:
            result = tools.compare_titles(title_a, title_b)
            return {
                "intent": "compare_titles",
                "reason": "found a comparison keyword ('compare'/'vs'/'versus') and split "
                          f"the rest into two titles: '{title_a}' and '{title_b}'",
                "tool_calls": [("compare_titles", {"title_a": title_a, "title_b": title_b})],
                "result": result,
                "response": format_comparison(result),
            }

    # 2. Mixed: "something like X (but shorter/longer)" -> look up X, then recommend
    like_match = LIKE_RE.search(query)
    if like_match:
        reference_title = like_match.group(1).strip(" ?.!")
        ref_lookup = tools.search_titles(reference_title, top_n=1)
        if ref_lookup["results"]:
            ref = ref_lookup["results"][0]
            max_runtime = extract_max_runtime(query)
            if max_runtime is None and "shorter" in query.lower() and ref["runtime"]:
                max_runtime = ref["runtime"]
            semantic_query = ref["overview"] or ref["title"]
            rec_result = tools.recommend(semantic_query, genres=ref["genres"], max_runtime=max_runtime)
            # Don't recommend the reference title back to itself.
            rec_result["results"] = [r for r in rec_result["results"] if r["uid"] != ref["uid"]]
            return {
                "intent": "mixed_search_then_recommend",
                "reason": f"query references a specific title ('like {reference_title}'), so "
                          "search_titles found it first, then its genres/overview were fed "
                          "into recommend() as the query and constraints",
                "tool_calls": [
                    ("search_titles", {"query": reference_title}),
                    ("recommend", {"query": semantic_query, "genres": ref["genres"],
                                    "max_runtime": max_runtime}),
                ],
                "result": {"reference": ref, "recommendations": rec_result},
                "response": format_recommend(rec_result, prefix=f"Because you liked {ref['title']}:"),
            }

    # 3. Recommend: descriptive/thematic ask
    if RECOMMEND_RE.search(query):
        genres = extract_genres(query)
        max_runtime = extract_max_runtime(query)
        min_rating = extract_min_rating(query)
        result = tools.recommend(query, genres=genres, max_runtime=max_runtime, min_rating=min_rating)
        return {
            "intent": "recommend",
            "reason": "found a recommend/suggest-style keyword; extracted structured "
                      f"constraints (genres={genres or None}, max_runtime={max_runtime}, "
                      f"min_rating={min_rating}) and used the full query as the semantic search text",
            "tool_calls": [("recommend", {"query": query, "genres": genres,
                                            "max_runtime": max_runtime, "min_rating": min_rating})],
            "result": result,
            "response": format_recommend(result),
        }

    # 4. Filter: mostly structural constraints, little descriptive content
    genres = extract_genres(query)
    max_runtime = extract_max_runtime(query)
    min_rating = extract_min_rating(query)
    year_min, year_max = extract_year_bounds(query)
    media_type = extract_media_type(query)
    has_constraint = any([genres, max_runtime, min_rating, year_min, year_max, media_type])

    if has_constraint:
        result = tools.filter_by_constraints(
            genres=genres, media_type=media_type, year_min=year_min, year_max=year_max,
            max_runtime=max_runtime, min_rating=min_rating,
        )
        return {
            "intent": "filter_by_constraints",
            "reason": f"no comparison/recommend/reference-title signal found, but structural "
                      f"constraints were present (genres={genres or None}, media_type={media_type}, "
                      f"year=[{year_min}, {year_max}], max_runtime={max_runtime}, min_rating={min_rating})",
            "tool_calls": [("filter_by_constraints", {
                "genres": genres, "media_type": media_type, "year_min": year_min,
                "year_max": year_max, "max_runtime": max_runtime, "min_rating": min_rating,
            })],
            "result": result,
            "response": format_filter(result),
        }

    # 5. Fallback: title/keyword lookup
    lookup_text = strip_lookup_phrases(query) or query
    result = tools.search_titles(lookup_text, top_n=5)
    return {
        "intent": "search_titles",
        "reason": "no comparison, recommendation, or constraint signal found - "
                  "treating this as a plain title/keyword lookup",
        "tool_calls": [("search_titles", {"query": lookup_text})],
        "result": result,
        "response": format_lookup(result),
    }
