"""
Day 4: evidence display + hallucination guardrails.

Three pieces:

1. build_evidence() - a consistent {title, excerpt, score, source} record
   for whatever a tool returned, so every response can show exactly what
   backed it.

2. validate_titles() - checks that every title an evidence list claims
   actually exists in the dataset. Because every response in this system
   is built directly from tools.py's structured output (nothing is
   generated by a language model), this should always pass today - but
   it's real, working validation, not a stub. It's what would catch a
   hallucinated title the moment any free-text generation gets added on
   top of this, and it also catches pipeline bugs (e.g. a formatter
   accidentally referencing the wrong record).

3. has_sufficient_confidence() - a threshold on retrieval strength. Below
   it, the agent should say it doesn't have enough reliable information
   rather than presenting weak matches as if they were good ones.

   The thresholds were calibrated empirically, not guessed: we measured
   raw (non-pool-normalized) semantic similarity and BM25 scores for five
   clearly-relevant queries vs. five clearly-vague ones ("stuff",
   "something good", nonsense text). Relevant queries scored semantic
   >= 0.43 and BM25 >= 18; vague ones stayed below 0.37 and 10.5. The
   thresholds sit in that gap. Note this specifically uses RAW BM25
   scores, not ranking.py's normalized bm25_score - that score is
   min-max normalized *within each query's candidate pool*, so it always
   stretches to fill 0-1 even when every match in the pool is weak, which
   makes it useless as an absolute confidence signal.

This is a shared module - other scripts import it, it isn't run directly.
"""

import re

import tools

CONFIDENCE_SEM_THRESHOLD = 0.40
CONFIDENCE_BM25_THRESHOLD = 15.0

LOW_CONFIDENCE_MESSAGE = (
    "I don't have enough reliable information to answer that confidently. "
    "Try rephrasing with more specific details - a genre, a plot description, "
    "or a title."
)


def has_sufficient_confidence(top_semantic_raw, top_bm25_raw):
    sem_ok = (top_semantic_raw or 0.0) >= CONFIDENCE_SEM_THRESHOLD
    bm25_ok = (top_bm25_raw or 0.0) >= CONFIDENCE_BM25_THRESHOLD
    return sem_ok or bm25_ok


def build_evidence(title, source, excerpt, score):
    """One evidence entry: which title, how it was found, a snippet of
    the actual text that justified including it, and the score (if any
    similarity/relevance score applies to that retrieval method)."""
    return {
        "title": title,
        "source": source,
        "excerpt": (excerpt or "").strip().replace("\n", " ")[:300],
        "score": score,
    }


def render_evidence(evidence_list):
    """Plain-text evidence block appended to every response, so you can
    see exactly what backed the answer: which title, how it was found,
    what score (if any) applied, and the actual excerpt of text."""
    if not evidence_list:
        return "Evidence: (none)"
    lines = ["Evidence:"]
    for e in evidence_list:
        score_str = f"{e['score']:.3f}" if isinstance(e["score"], (int, float)) else "n/a"
        lines.append(f"  - {e['title']}  [source: {e['source']}, score: {score_str}]")
        if e["excerpt"]:
            lines.append(f'    "{e["excerpt"]}"')
    return "\n".join(lines)


def scan_text_for_titles(text):
    """Which dataset titles appear as whole words in a piece of free
    text. This is the check that matters once something actually
    generates prose (like llm_agent.py): compare the titles found here
    against the evidence a response was given, to catch a title being
    mentioned without anything backing it. Titles shorter than 4
    characters are skipped to avoid false positives on short/common words.

    Uses word-boundary matching, not raw substring containment - a plain
    `"vera" in text` would match the "vera" hiding inside "ove-VERA-ll",
    which is a real false positive this caught in testing.
    """
    text_lower = text.lower()
    found = []
    for t in tools.known_titles():
        if len(t) < 4:
            continue
        if re.search(r"\b" + re.escape(t.lower()) + r"\b", text_lower):
            found.append(t)
    return found


def validate_titles(evidence_list):
    """Check every title in an evidence list against the real dataset.
    Returns (clean_evidence, flagged_titles). Titles that don't exist in
    the dataset are removed from clean_evidence and reported separately
    rather than silently dropped."""
    catalog = tools.known_titles()
    clean, flagged = [], []
    for entry in evidence_list:
        if entry["title"] in catalog:
            clean.append(entry)
        else:
            flagged.append(entry["title"])
    return clean, flagged
